Task/35 save store
HaronCode/Gemini pull request #26
Opened 2020-08-27 16:54 UTC by HaronCode

Добавил функциональность сохранения ConnectionRuleFactory вместе со Store между переворотами. Теперь не важно как устроены скоупы в DI фреймворке, лита сама все сделает.

API немного поменял, как мне кажется сделал его довольно простым и лаконичным, но хз возможно есть идеи как будет лучше.

2020-08-31 14:00 UTC, HaronCode commented
Сделал небольшой рефакторинг, вынес интерфейс Binder. Дальше его можно развить и допустим вынести в общий модуль коннектор и сделать общую логику, пока сделал так.

2020-08-31 16:44 UTC, kdk96 requested changes

2020-08-31 16:44 UTC, kdk96 commented on gemini-android/src/main/java/com/haroncode/gemini/android/binder/StoreViewBinding.kt
> +    @JvmStatic
убираемс

2020-08-31 16:44 UTC, kdk96 commented on gemini-android/src/main/java/com/haroncode/gemini/android/lifecycle/ExtendedLifecycleObserver.kt
> +internal abstract class ExtendedLifecycleObserver : LifecycleObserver, SavedStateRegistry.SavedStateProvider {
вообще конечно возможно для кого то был бы полезной вещью

2020-08-31 16:44 UTC, kdk96 commented on gemini-android/src/main/java/com/haroncode/gemini/android/binder/RestoreBinder.kt
> +                bundle?.getString(KEY_FACTORY_NAME) ?: run { createNewName() }
во первых `run` не нужен, во вторых я бы exception кидал, ибо дичь какая-то происходит значит

2020-08-31 16:44 UTC, kdk96 commented on gemini-android/src/main/java/com/haroncode/gemini/android/binder/RestoreBinder.kt
> +        companion object {
companion вниз, kotlin codestyle увы

2020-08-31 16:44 UTC, kdk96 commented on gemini-android/src/main/java/com/haroncode/gemini/android/binder/RestoreBinder.kt
> +        private fun createNewName(): String = "${TAG}_${stateRegistry.hashCode()}"
для factory name `hashCode` `stateRegistry` чет прям не очень, может UUID заюзаем тогда? типо вдруг я две разные фактори на одном экране как то хочу замутить

2020-08-31 16:44 UTC, kdk96 commented on gemini-android/src/main/java/com/haroncode/gemini/android/binder/RestoreBinder.kt
> +            stateRegistry.registerSavedStateProvider(KEY_FACTORY_SAVER_NAME) {
здесь упадет, если две разные фактори попробую зарегать, тут короче надо прям provider делать, которому можно будет класть в коллекцию и он потом все имена будет сохранять

2020-08-31 16:44 UTC, kdk96 commented on gemini-android/src/main/java/com/haroncode/gemini/android/binder/RestoreBinder.kt
> +            private const val TAG = "store_view"
не оч кажется тэг, мб factory надо добавить

2020-08-31 16:44 UTC, kdk96 commented on gemini-android/src/main/java/com/haroncode/gemini/android/binder/RestoreBinder.kt
> +            private const val KEY_FACTORY_SAVER_NAME = "factory_saver_name"
на всякий случай можно добавить gemini префикс, чтобы наверняка нигде коллизий не было

2020-08-31 16:48 UTC, HaronCode commented on gemini-android/src/main/java/com/haroncode/gemini/android/binder/RestoreBinder.kt
> +            stateRegistry.registerSavedStateProvider(KEY_FACTORY_SAVER_NAME) {
Так стоп, не может быть разных factory, подразумевается что она factory на один экран/фрагмент/view в которой ты можешь заиспользовать тучу Store. Я пока не особо вижу смысла в этой фиче, можно будет добавить это позже

2020-08-31 16:49 UTC, HaronCode commented on gemini-android/src/main/java/com/haroncode/gemini/android/lifecycle/ExtendedLifecycleObserver.kt
> +internal abstract class ExtendedLifecycleObserver : LifecycleObserver, SavedStateRegistry.SavedStateProvider {
В этом то как мне кажется и проблема, не стоит делать так, чтобы у клиентов был соблазн на него завязываться. Фиг знает как мы его еще поменяем со временем.

2020-09-01 07:39 UTC, HaronCode commented on gemini-android/src/main/java/com/haroncode/gemini/android/binder/RestoreBinder.kt
> +                bundle?.getString(KEY_FACTORY_NAME) ?: run { createNewName() }
он все же нужен, он при первом обращении выдает bundle как null

2020-09-01 07:43 UTC, HaronCode commented on gemini-android/src/main/java/com/haroncode/gemini/android/binder/RestoreBinder.kt
> +            stateRegistry.registerSavedStateProvider(KEY_FACTORY_SAVER_NAME) {
Вынес в отдельную задачу, пока просто кидаю понятный exception

2020-09-01 08:13 UTC, kdk96 commented on gemini-android/src/main/java/com/haroncode/gemini/android/binder/BindingRulesFactoryManager.kt
> +    fun <T : Any> restoreFactory(tag: String): BindingRulesFactory<T>? {
добавь suppress

2020-09-01 08:29 UTC, kdk96 approved these changes

2020-09-01 08:36 UTC, merged